# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Eliot.UEExplorer
PackageVersion: 1.3.1
PackageLocale: en-US
Publisher: Eliot
PackageName: UE Explorer
License: MIT License
ShortDescription: UnrealScript decompiler and explorer tool for Unreal Engine packages.
ManifestType: defaultLocale
ManifestVersion: 1.2.0

