# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Eliot.UEExplorer
PackageVersion: 1.3.1
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  InstallerUrl: https://eliotvu.com/updates/ue-explorer.1.3.1.0.msi
  InstallerSha256: F1AF3EF606C7E4B0A8694ABA0943840A2C815331FC232FA1904F4F10444A8CA9
  ProductCode: '{E29ADE45-052E-4CD4-9B13-0D106DA1CB49}'
ManifestType: installer
ManifestVersion: 1.2.0

